import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Terms & Conditions — de_cooper.ai",
    description: "Terms of use, parody disclaimer, and legal notices for de_cooper.ai — a satirical fan project.",
};

export default function TermsPage() {
    return (
        <div className="min-h-dvh bg-primary">
            {/* Header */}
            <div className="border-b border-secondary px-6 py-6">
                <div className="mx-auto max-w-3xl flex items-center justify-between">
                    <Link href="/" className="font-logo text-xl font-extrabold text-primary tracking-tight">
                        de_cooper.ai
                    </Link>
                    <Link href="/" className="text-xs text-tertiary hover:text-primary transition-colors">
                        ← Back to Home
                    </Link>
                </div>
            </div>

            {/* Content */}
            <div className="mx-auto max-w-3xl px-6 py-16">
                <h1 className="font-logo text-4xl font-extrabold text-primary tracking-tight">
                    Terms &amp; Conditions
                </h1>
                <p className="mt-2 text-sm text-tertiary">
                    Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
                </p>

                <div className="mt-10 space-y-10 text-sm text-secondary leading-relaxed">
                    {/* Section 1 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">1. Nature of This Project</h2>
                        <p>
                            de_cooper.ai (&ldquo;the Platform&rdquo;) is a <strong>non-commercial, satirical fan project</strong> created
                            exclusively for educational and comedic purposes. The Platform employs the persona of a fictional character
                            as a humorous framing device for AI-assisted learning. It is not a commercial product, does not generate
                            revenue, and is not offered for sale.
                        </p>
                    </section>

                    {/* Section 2 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">2. Parody &amp; Satire Disclaimer</h2>
                        <p>
                            This Platform constitutes <strong>parody and transformative commentary</strong> under fair use principles
                            (17 U.S.C. § 107). The character &ldquo;Dr. Sheldon Cooper&rdquo; is a fictional character from the
                            television series <em>The Big Bang Theory</em>, created by Chuck Lorre and Bill Prady.
                        </p>
                        <p className="mt-3">
                            All related names, characters, likenesses, and trademarks are the property of their respective owners,
                            including but not limited to CBS Studios Inc., Warner Bros. Television, and Chuck Lorre Productions.
                        </p>
                        <p className="mt-3">
                            This Platform is <strong>not affiliated with, endorsed by, sponsored by, or in any way officially
                            connected with</strong> any of the aforementioned entities, their subsidiaries, or their affiliates.
                            Any resemblance to the fictional character is intended purely as satirical commentary.
                        </p>
                    </section>

                    {/* Section 3 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">3. No Warranty &amp; Educational Disclaimer</h2>
                        <p>
                            The educational content provided on this Platform is generated by artificial intelligence and is presented
                            &ldquo;as is&rdquo; without any warranties, express or implied. The AI-generated responses are for
                            entertainment and general educational purposes only and should not be relied upon as authoritative
                            academic instruction.
                        </p>
                        <p className="mt-3">
                            We make no guarantees regarding the accuracy, completeness, or reliability of any content generated
                            by the Platform. Users should independently verify any information before relying on it for academic,
                            professional, or any other purposes.
                        </p>
                    </section>

                    {/* Section 4 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">4. User Accounts &amp; Data</h2>
                        <p>
                            When you create an account, you agree to provide accurate information. We store only the minimum data
                            required to operate the Platform: your email address, a hashed password, and your conversation history
                            with the AI tutor.
                        </p>
                        <p className="mt-3">
                            We do not sell, share, or distribute your personal data to third parties. Your conversation data is
                            stored solely to provide continuity of your learning sessions. You may request deletion of your account
                            and all associated data at any time.
                        </p>
                    </section>

                    {/* Section 5 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">5. Acceptable Use</h2>
                        <p>You agree not to use this Platform to:</p>
                        <ul className="mt-2 list-disc list-inside space-y-1 text-tertiary">
                            <li>Engage in any unlawful, harmful, or abusive activity</li>
                            <li>Attempt to extract, reverse-engineer, or scrape the AI model or its responses</li>
                            <li>Misrepresent AI-generated content as human-authored academic work</li>
                            <li>Overload the Platform with automated requests or denial-of-service attacks</li>
                            <li>Use the Platform for any commercial purpose</li>
                        </ul>
                    </section>

                    {/* Section 6 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">6. Intellectual Property</h2>
                        <p>
                            The original code, design, and user interface of this Platform are the work of its creator(s). The
                            satirical persona, character references, and associated trademarks belong to their respective rights
                            holders as noted in Section 2.
                        </p>
                        <p className="mt-3">
                            If you are a rights holder and believe that any content on this Platform infringes your intellectual
                            property rights, please contact us. We will review and address all legitimate concerns promptly and
                            in good faith.
                        </p>
                    </section>

                    {/* Section 7 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">7. Limitation of Liability</h2>
                        <p>
                            To the fullest extent permitted by applicable law, the creators of this Platform shall not be liable
                            for any indirect, incidental, special, consequential, or punitive damages arising out of or relating
                            to your use of, or inability to use, the Platform. This includes, without limitation, damages for
                            loss of profits, data, or other intangible losses.
                        </p>
                    </section>

                    {/* Section 8 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">8. Changes to These Terms</h2>
                        <p>
                            We reserve the right to modify these Terms at any time. Continued use of the Platform after any
                            changes constitutes acceptance of the updated Terms. We will make reasonable efforts to notify users
                            of material changes.
                        </p>
                    </section>

                    {/* Section 9 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">9. Contact</h2>
                        <p>
                            For any questions, concerns, or takedown requests regarding this Platform, please open an issue on
                            the project&apos;s GitHub repository or contact the project maintainer directly.
                        </p>
                    </section>
                </div>

                {/* Sheldon sign-off */}
                <div className="mt-16 rounded-xl border border-secondary bg-secondary/30 p-6 text-center">
                    <p className="text-xs italic text-tertiary">
                        &ldquo;I would say I&apos;m sorry, but I was right. And that feels better than being sorry.&rdquo;
                    </p>
                    <p className="mt-2 text-[10px] font-mono text-quaternary uppercase tracking-wider">
                        // Dr. Cooper, on writing legal disclaimers
                    </p>
                </div>
            </div>
        </div>
    );
}
