import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Terms & Conditions — de_study.ai",
    description: "Terms of use and platform agreements for de_study.ai — premium visual-first STEM calendar workspace.",
};

export default function TermsPage() {
    return (
        <div className="min-h-dvh bg-primary">
            {/* Header */}
            <div className="border-b border-secondary px-6 py-6">
                <div className="mx-auto max-w-3xl flex items-center justify-between">
                    <Link href="/" className="font-logo text-xl font-extrabold text-primary tracking-tight">
                        de_study.ai
                    </Link>
                    <Link href="/" className="text-xs text-tertiary hover:text-primary transition-colors">
                        ← Back to Home
                    </Link>
                </div>
            </div>

            {/* Content */}
            <div className="mx-auto max-w-3xl px-6 py-16">
                <h1 className="font-logo text-4xl font-extrabold text-primary tracking-tight">
                    Terms &amp; Conditions
                </h1>
                <p className="mt-2 text-sm text-tertiary">
                    Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
                </p>

                <div className="mt-10 space-y-10 text-sm text-secondary leading-relaxed">
                    {/* Section 1 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">1. Nature of the Platform</h2>
                        <p>
                            de_study.ai (&ldquo;the Platform&rdquo;) is an advanced, AI-powered STEM learning and workspace
                            environment. The Platform provides users with interactive study schedules, spaced repetition
                            calendars, visual-first conceptual slides, and customized flashcard generation to optimize the
                            educational workflow.
                        </p>
                    </section>

                    {/* Section 2 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">2. AI Assistance &amp; Content Disclaimer</h2>
                        <p>
                            The educational explanations, diagrams, mathematical derivations, and flashcards provided on this Platform
                            are generated by cutting-edge artificial intelligence systems. While we continually strive for absolute academic
                            precision, all AI-generated content is provided &ldquo;as is&rdquo; without warranties of any kind. Users are
                            encouraged to cross-verify complex formulas, equations, and derivations with standard textbook materials.
                        </p>
                        <p className="mt-3">
                            We make no guarantees regarding the absolute accuracy, completeness, or reliability of any content generated
                            by the Platform. Users should independently verify any information before relying on it for academic,
                            professional, or any other purposes.
                        </p>
                    </section>

                    {/* Section 3 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">3. User Accounts &amp; Data Security</h2>
                        <p>
                            To access personalized learning boards, calendar schedules, and lesson history, you must register an account.
                            We protect your privacy by storing only required metrics (e.g., email address, securely hashed credentials,
                            and conversation logs). Your learning history is stored solely to provide session continuity and flashcard
                            recall. We do not sell or distribute your personal data.
                        </p>
                        <p className="mt-3">
                            Your conversation data is stored solely to provide continuity of your learning sessions. You may request deletion
                            of your account and all associated data at any time by contacting our support channels.
                        </p>
                    </section>

                    {/* Section 4 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">4. Acceptable Use Policy</h2>
                        <p>You agree to utilize de_study.ai only for legitimate educational purposes. You shall not:</p>
                        <ul className="mt-2 list-disc list-inside space-y-1 text-tertiary">
                            <li>Engage in any abusive, malicious, or scraping operations against our backend APIs</li>
                            <li>Attempt to reverse-engineer or extract raw weights from the primary AI services</li>
                            <li>Misrepresent automated answers as your own unassisted academic output where forbidden</li>
                            <li>Use the system in any manner that impairs or degrades the experience for other learners</li>
                        </ul>
                    </section>

                    {/* Section 5 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">5. Intellectual Property</h2>
                        <p>
                            The core system code, responsive user interface assets, styled components, and visual layouts of
                            de_study.ai are the proprietary property of the platform maintainers. Flashcards, session notes,
                            and study schedules generated for individual user accounts remain the personal property of the respective users.
                        </p>
                    </section>

                    {/* Section 6 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">6. Limitation of Liability</h2>
                        <p>
                            To the maximum extent permitted by applicable law, de_study.ai and its creators shall not be held liable
                            for any academic marks, test grades, or administrative outcomes. We are not responsible for any indirect,
                            incidental, or consequential losses associated with system downtime or incorrect AI-generated equations.
                        </p>
                    </section>

                    {/* Section 7 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">7. Changes to These Terms</h2>
                        <p>
                            We reserve the right to modify these Terms at any time. Continued use of the Platform after any
                            changes constitutes acceptance of the updated Terms. We will make reasonable efforts to notify users
                            of material changes.
                        </p>
                    </section>

                    {/* Section 8 */}
                    <section>
                        <h2 className="text-lg font-semibold text-primary mb-3">8. Contact</h2>
                        <p>
                            For any questions, concerns, or inquiries regarding the Platform or your account data, please open an
                            issue on our project repository or reach out to the project administrators.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
