"use client";

import { useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface TermsModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export function TermsModal({ isOpen, onClose }: TermsModalProps) {
    const contentRef = useRef<HTMLDivElement>(null);

    // Lock body scroll when open
    useEffect(() => {
        if (isOpen) {
            document.body.style.overflow = "hidden";
        } else {
            document.body.style.overflow = "";
        }
        return () => {
            document.body.style.overflow = "";
        };
    }, [isOpen]);

    // Close on Escape
    useEffect(() => {
        const handleKey = (e: KeyboardEvent) => {
            if (e.key === "Escape") onClose();
        };
        if (isOpen) window.addEventListener("keydown", handleKey);
        return () => window.removeEventListener("keydown", handleKey);
    }, [isOpen, onClose]);

    return (
        <AnimatePresence>
            {isOpen && (
                <>
                    {/* Backdrop */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.2 }}
                        className="fixed inset-0 z-[100] bg-black/50 backdrop-blur-sm"
                        onClick={onClose}
                    />

                    {/* Modal Panel */}
                    <motion.div
                        initial={{ opacity: 0, y: 40, scale: 0.97 }}
                        animate={{ opacity: 1, y: 0, scale: 1 }}
                        exit={{ opacity: 0, y: 20, scale: 0.97 }}
                        transition={{ type: "spring", stiffness: 300, damping: 28 }}
                        className="fixed inset-x-4 top-[5%] bottom-[5%] z-[101] mx-auto max-w-3xl rounded-2xl border border-secondary bg-primary shadow-2xl flex flex-col overflow-hidden"
                    >
                        {/* Header */}
                        <div className="flex items-center justify-between border-b border-secondary px-6 py-4 shrink-0">
                            <div>
                                <h2 className="font-logo text-xl font-extrabold text-primary tracking-tight">
                                    Terms &amp; Conditions
                                </h2>
                                <p className="text-[10px] text-tertiary mt-0.5">
                                    Last updated: May 2026
                                </p>
                            </div>
                            <button
                                onClick={onClose}
                                className="flex items-center justify-center size-8 rounded-lg border border-secondary bg-secondary/30 text-tertiary hover:text-primary hover:bg-secondary transition-all text-sm font-mono"
                            >
                                ✕
                            </button>
                        </div>

                        {/* Scrollable Content */}
                        <div ref={contentRef} className="flex-1 overflow-y-auto px-6 py-8 space-y-8 text-sm text-secondary leading-relaxed">
                            <section>
                                <h3 className="text-base font-semibold text-primary mb-2">1. Nature of the Platform</h3>
                                <p>
                                    de_study.ai (&ldquo;the Platform&rdquo;) is an advanced, AI-powered STEM learning and workspace
                                    environment. The Platform provides users with interactive study schedules, spaced repetition
                                    calendars, visual-first conceptual slides, and customized flashcard generation to optimize the
                                    educational workflow.
                                </p>
                            </section>

                            <section>
                                <h3 className="text-base font-semibold text-primary mb-2">2. AI Assistance &amp; Content Disclaimer</h3>
                                <p>
                                    The educational explanations, diagrams, mathematical derivations, and flashcards provided on this Platform
                                    are generated by cutting-edge artificial intelligence systems. While we continually strive for absolute academic
                                    precision, all AI-generated content is provided &ldquo;as is&rdquo; without warranties of any kind. Users are
                                    encouraged to cross-verify complex formulas, equations, and derivations with standard textbook materials.
                                </p>
                            </section>

                            <section>
                                <h3 className="text-base font-semibold text-primary mb-2">3. User Accounts &amp; Data Security</h3>
                                <p>
                                    To access personalized learning boards, calendar schedules, and lesson history, you must register an account.
                                    We protect your privacy by storing only required metrics (e.g., email address, securely hashed credentials,
                                    and conversation logs). Your learning history is stored solely to provide session continuity and flashcard
                                    recall. We do not sell or distribute your personal data.
                                </p>
                            </section>

                            <section>
                                <h3 className="text-base font-semibold text-primary mb-2">4. Acceptable Use Policy</h3>
                                <p>You agree to utilize de_study.ai only for legitimate educational purposes. You shall not:</p>
                                <ul className="mt-2 list-disc list-inside space-y-1 text-tertiary">
                                    <li>Engage in any abusive, malicious, or scraping operations against our backend APIs</li>
                                    <li>Attempt to reverse-engineer or extract raw weights from the primary AI services</li>
                                    <li>Misrepresent automated answers as your own unassisted academic output where forbidden</li>
                                    <li>Use the system in any manner that impairs or degrades the experience for other learners</li>
                                </ul>
                            </section>

                            <section>
                                <h3 className="text-base font-semibold text-primary mb-2">5. Intellectual Property</h3>
                                <p>
                                    The core system code, responsive user interface assets, styled components, and visual layouts of
                                    de_study.ai are the proprietary property of the platform maintainers. Flashcards, session notes,
                                    and study schedules generated for individual user accounts remain the personal property of the respective users.
                                </p>
                            </section>

                            <section>
                                <h3 className="text-base font-semibold text-primary mb-2">6. Limitation of Liability</h3>
                                <p>
                                    To the maximum extent permitted by applicable law, de_study.ai and its creators shall not be held liable
                                    for any academic marks, test grades, or administrative outcomes. We are not responsible for any indirect,
                                    incidental, or consequential losses associated with system downtime or incorrect AI-generated equations.
                                </p>
                            </section>
                        </div>

                        {/* Footer */}
                        <div className="border-t border-secondary px-6 py-4 shrink-0 flex items-center justify-between">
                            <p className="text-[10px] text-quaternary">
                                &copy; {new Date().getFullYear()} de_study.ai &mdash; Premium visual-first STEM workspace.
                            </p>
                            <button
                                onClick={onClose}
                                className="rounded-lg bg-brand-primary px-4 py-2 text-xs font-semibold text-white hover:bg-brand-primary/90 transition-colors"
                            >
                                I Understand
                            </button>
                        </div>
                    </motion.div>
                </>
            )}
        </AnimatePresence>
    );
}
